import { createHash } from "node:crypto";

/**
 * Short match key used to address rows in the Convex store and the ledger.
 *
 * SOURCE: this is a 1:1 TypeScript replication of `short_key()` in
 * src/dashboard.py:
 *
 *   def short_key(key: str) -> str:
 *       return hashlib.sha1(key.encode("utf-8")).hexdigest()[:12]
 *
 * I.e. the first 12 hex chars of the SHA-1 of the UTF-8 encoding of the
 * full match key. Parity is checked by scripts/shortkey-check.ts, whose
 * expected values were generated by running the Python function directly.
 */
export function shortKey(key: string): string {
  return createHash("sha1").update(key, "utf8").digest("hex").slice(0, 12);
}
