"""Adapter for company ATS boards: Greenhouse, Lever, and Ashby.

These are official, public, no-auth JSON APIs. Boards are listed in
data/ats_boards.yaml (generated by scripts/discover_ats_boards.py). Titles
are pre-filtered to intern/co-op here so a 2,000-role board doesn't flood
the pipeline; the per-user role filter still runs afterwards.
"""

from __future__ import annotations

import datetime as dt
import json
import logging
import re
from pathlib import Path

import httpx
import yaml

from ..models import Job
from ..normalize import infer_terms, split_locations, strip_html, strip_tracking
from . import smartrecruiters_api as sr
from .base import Adapter, fetch_text

log = logging.getLogger(__name__)

INTERN_RE = re.compile(r"\bintern(ship)?s?\b|\bco-?op\b", re.I)

JD_MAX_CHARS = 6000  # requirements sections usually live mid-document

_REPO_ROOT = Path(__file__).resolve().parents[2]

_API = {
    "greenhouse": "https://boards-api.greenhouse.io/v1/boards/{slug}/jobs",
    "lever": "https://api.lever.co/v0/postings/{slug}?mode=json",
    "ashby": "https://api.ashbyhq.com/posting-api/job-board/{slug}",
    "smartrecruiters": sr.LIST_URL,
}


def _lever_jd(j: dict) -> str | None:
    """Lever splits the JD: intro in descriptionPlain, the requirement
    bullets (where degree/clearance demands live) in `lists`, closing
    boilerplate in additionalPlain."""
    parts = [j.get("descriptionPlain") or ""]
    for section in j.get("lists") or []:
        parts.append(section.get("text") or "")
        parts.append(strip_html(section.get("content") or ""))
    parts.append(j.get("additionalPlain") or "")
    text = " ".join(p for p in parts if p).strip()
    return text or None


def _iso_date(value: str | None) -> dt.date | None:
    if not value:
        return None
    try:
        return dt.datetime.fromisoformat(value.replace("Z", "+00:00")).date()
    except ValueError:
        return None


class AtsBoardsAdapter(Adapter):
    def fetch(self, client: httpx.Client, today: dt.date) -> list[Job]:
        boards_path = _REPO_ROOT / (self.cfg.boards_file or "data/ats_boards.yaml")
        boards = yaml.safe_load(boards_path.read_text(encoding="utf-8"))["boards"]
        jobs: list[Job] = []
        failures = 0
        for board in boards:
            url = _API[board["ats"]].format(slug=board["slug"])
            try:
                raw = fetch_text(client, url)
                parsed = self.parse(
                    raw, f"{board['ats']}:{board['slug']}:{board['company']}",
                    today)
            except Exception as exc:  # noqa: BLE001 - one board never kills the source
                failures += 1
                log.warning("ats board %s/%s failed: %s",
                            board["ats"], board["slug"], exc)
                continue
            jobs.extend(parsed)
        log.info("source %s: %d intern postings from %d boards (%d failed)",
                 self.cfg.name, len(jobs), len(boards), failures)
        return jobs

    def parse(self, raw: str, path: str, today: dt.date) -> list[Job]:
        """path is '{ats}:{slug}:{company}' -- keeps the base-class contract
        so the per-ATS parsers are testable against fixtures without network.
        Lever/Ashby ship the JD inline; Greenhouse lists carry no content, so
        those jobs get a jd_url for main.enrich_jds to fetch lazily."""
        ats, slug, company = path.split(":", 2)
        data = json.loads(raw)
        rows = {
            "greenhouse": lambda: [
                (j.get("title"), j.get("absolute_url"),
                 (j.get("location") or {}).get("name", ""),
                 _iso_date(j.get("first_published") or j.get("updated_at")),
                 None,
                 _API["greenhouse"].format(slug=slug) + f"/{j['id']}"
                 if j.get("id") else None)
                for j in data.get("jobs", [])],
            "lever": lambda: [
                (j.get("text"), j.get("hostedUrl"),
                 (j.get("categories") or {}).get("location", ""),
                 dt.datetime.fromtimestamp(j["createdAt"] / 1000,
                                           tz=dt.timezone.utc).date()
                 if j.get("createdAt") else None,
                 _lever_jd(j), None)
                for j in data if isinstance(j, dict)],
            "ashby": lambda: [
                (j.get("title"), j.get("jobUrl"),
                 " / ".join(filter(None, [j.get("location")] + [
                     s.get("location") for s in j.get("secondaryLocations") or []])),
                 _iso_date(j.get("publishedAt")),
                 (j.get("descriptionPlain")
                  or strip_html(j.get("descriptionHtml") or "") or None),
                 None)
                for j in data.get("jobs", []) if j.get("isListed", True)],
            "smartrecruiters": lambda: [
                (j.get("name"), sr.posting_url(j, slug),
                 sr.location_str(j),
                 _iso_date(j.get("releasedDate")),
                 None,
                 sr.DETAIL_URL.format(slug=slug, posting_id=j["id"])
                 if j.get("id") else None)
                for j in data.get("content", [])],
        }[ats]()

        jobs: list[Job] = []
        for title, url, location, date_posted, description, jd_url in rows:
            if not title or not url or not INTERN_RE.search(title):
                continue
            terms, confidence = infer_terms(title, today)
            jobs.append(Job(
                company=company,
                title=title.strip(),
                locations=split_locations(location or ""),
                terms=terms,
                term_confidence=confidence,
                url=strip_tracking(url),
                date_posted=date_posted,
                description=description[:JD_MAX_CHARS] if description else None,
                jd_url=jd_url,
                source=self.cfg.name,
            ))
        return jobs
