"""Discover which companies from data/*.txt have public ATS job boards.

    python scripts/discover_ats_boards.py

Probes the official public JSON APIs of Greenhouse, Lever, and Ashby with
slug candidates derived from each company's name and aliases, then writes
data/ats_boards.yaml (sorted, stable). Re-run any time the company lists
change; review the diff before committing -- a short alias can occasionally
match an unrelated company's board.
"""

from __future__ import annotations

import asyncio
import re
import sys
from pathlib import Path

import httpx
import yaml

ROOT = Path(__file__).resolve().parent.parent
COMPANY_FILES = ["data/top_companies.txt", "data/atlanta_companies.txt"]
OUT_PATH = ROOT / "data" / "ats_boards.yaml"

CONCURRENCY = 12
MIN_SLUG_LEN = 3   # 1-2 char slugs ("ea") collide too easily


def load_companies() -> list[tuple[str, list[str]]]:
    """[(canonical, [name variants...])]"""
    out = []
    for rel in COMPANY_FILES:
        for line in (ROOT / rel).read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            names = [n.strip() for n in line.split("|") if n.strip()]
            if names:
                out.append((names[0], names))
    return out


def slug_candidates(names: list[str]) -> list[str]:
    cands: list[str] = []
    for name in names:
        clean = re.sub(r"[^a-z0-9 ]", "", name.lower().replace("&", " and "))
        clean = re.sub(r"\s+", " ", clean).strip()
        if not clean:
            continue
        joined = clean.replace(" ", "")
        hyphen = clean.replace(" ", "-")
        for c in (joined, hyphen):
            if len(c) >= MIN_SLUG_LEN and c not in cands:
                cands.append(c)
    return cands


def sr_slug_candidates(names: list[str]) -> list[str]:
    """SmartRecruiters company-ids are PascalCase with no separators
    ("Visa", "McDonalds"), so add those on top of the lower-case forms."""
    cands = list(slug_candidates(names))
    for name in names:
        cleaned = name.replace("&", " and ").replace("'", "").replace("’", "")
        words = re.findall(r"[A-Za-z0-9]+", cleaned)
        pascal = "".join(w[:1].upper() + w[1:] for w in words)
        if len(pascal) >= MIN_SLUG_LEN and pascal not in cands:
            cands.append(pascal)
    return cands


async def probe(client: httpx.Client, ats: str, slug: str) -> bool:
    urls = {
        "greenhouse": f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs",
        "lever": f"https://api.lever.co/v0/postings/{slug}?limit=1&mode=json",
        "ashby": f"https://api.ashbyhq.com/posting-api/job-board/{slug}",
        "smartrecruiters": ("https://api.smartrecruiters.com/v1/companies/"
                            f"{slug}/postings?limit=1"),
    }
    try:
        resp = await client.get(urls[ats])
        if resp.status_code != 200:
            return False
        data = resp.json()
        # Require at least one posting: Ashby answers 200 + empty jobs for ANY
        # slug (phantom boards), and an empty Greenhouse/Lever board is stale.
        if ats == "lever":
            return isinstance(data, list) and len(data) > 0
        if ats == "smartrecruiters":
            # SmartRecruiters answers 200 with totalFound 0 for unknown slugs.
            return bool(data.get("content"))
        jobs = data.get("jobs")
        return isinstance(jobs, list) and len(jobs) > 0
    except Exception:  # noqa: BLE001
        return False


async def discover() -> list[dict]:
    companies = load_companies()
    sem = asyncio.Semaphore(CONCURRENCY)
    found: list[dict] = []

    async with httpx.AsyncClient(timeout=15.0, headers={
            "User-Agent": "intern-watch board discovery"}) as client:

        async def check_company(canonical: str, names: list[str]) -> None:
            for ats in ("greenhouse", "lever", "ashby", "smartrecruiters"):
                cands = (sr_slug_candidates(names) if ats == "smartrecruiters"
                         else slug_candidates(names))
                for slug in cands:
                    async with sem:
                        ok = await probe(client, ats, slug)
                    if ok:
                        found.append({"company": canonical, "ats": ats,
                                      "slug": slug})
                        print(f"  {canonical}: {ats}/{slug}")
                        break   # one slug per ATS is enough

        await asyncio.gather(*(check_company(c, ns) for c, ns in companies))
    return found


def main() -> int:
    boards = sorted(discover_sync(), key=lambda b: (b["company"].lower(), b["ats"]))
    OUT_PATH.write_text(
        "# Generated by scripts/discover_ats_boards.py -- review before committing.\n"
        "# A company may legitimately appear on multiple ATS (migrations);\n"
        "# delete rows that look stale or wrong.\n"
        + yaml.safe_dump({"boards": boards}, sort_keys=False),
        encoding="utf-8")
    companies = {b["company"] for b in boards}
    print(f"\n{len(boards)} boards across {len(companies)} companies "
          f"-> {OUT_PATH.relative_to(ROOT)}")
    return 0


def discover_sync() -> list[dict]:
    return asyncio.run(discover())


if __name__ == "__main__":
    sys.exit(main())
